platform :ios, '7.0'

pod 'DeskCommon', :git => 'git@github.com:forcedotcom/DeskCommon-Cocoa.git', :tag => '1.0.3'

target 'DeskAPIClientTests', :exclusive => true do
    pod 'Expecta', '~>0.3.1'
    pod 'OCMock', '~>3.0.2'
    pod 'OHHTTPStubs', '~>3.1.9'
    pod 'DeskCommonTest', :git => 'git@github.com:forcedotcom/DeskCommonTest-Cocoa.git'
end
